# <span style="color:green"><ins>Chapitre 2: Vecteurs, matrices et systèmes linéaires</ins></span>

In [1]:
import numpy as np

Dans ce chapitre, nous allons présenter quelques fonctions de la sous-librairie "linalg" de numpy (linear algebra). La liste exhaustive de toutes les fonctions disponibles est présentée sous le lien suivant :
https://numpy.org/doc/stable/reference/routines.linalg.html

## 2.1 Matrices et vecteurs : syntaxe

On supposera toujours que les matrices et vecteurs sont définis comme des tableaux numpy comme suit :<br/>
Pour définir
\begin{equation*}
A=
\left(
\begin{matrix}
1 & 2\\
3 & 4
\end{matrix}
\right)
\end{equation*}
On code :

In [2]:
A=np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


Pour définir
\begin{equation*}
A=
\left(
\begin{matrix}
1\\
2
\end{matrix}
\right)
\end{equation*}
On code :

In [3]:
A=np.array([[1],[2]])
print(A)

[[1]
 [2]]


Pour définir
\begin{equation*}
A=
\left(
\begin{matrix}
1 & 2
\end{matrix}
\right)
\end{equation*}
On code :

In [4]:
A=np.array([[1,2]])
print(A)

[[1 2]]


On notera que les matrices créées ci-dessus sont de type entier, ce qui peut potentiellement causer des problèmes d'overflow. Si le risque existe, il est préférable de travailler avec des *réels* : 

In [5]:
A=np.array([[1.,2.],[3.,4.]])
print(A)

[[1. 2.]
 [3. 4.]]


ou bien 

In [6]:
A=np.array([[1,2],[3,4]],dtype=np.float64)    # floating point number sur 64 bits
print(A)

[[1. 2.]
 [3. 4.]]


## 2.2 Opérations matricielles versus opérations terme à terme

### La règle

Lorsqu'on écrit `A@B`, c'est une multiplication matricielle, les dimensions de $A$ et $B$ doivent donc satisfaire les propriétés matricielles.<br/>
Lorsqu'on écrit `A*B`, `A/B` ou `A**B`, ce sont des opérations terme à terme (l'opérateur s'applique entre les mêmes composantes de $A$ et $B$). $A$ et $B$ doivent donc avoir la même dimension.

### Exemple 1

Soient les matrices suivantes :

In [7]:
A=np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [8]:
B=np.array([[5,0],[2,1]])
print(B)

[[5 0]
 [2 1]]


`A@B` va donner la multiplication matricielle, et `A*B` va donner la multiplication terme à terme (élément (i,j) de $A$ multiplié par l'élément (i,j) de $B$) :

In [9]:
print(A@B)

[[ 9  2]
 [23  4]]


In [10]:
print(A*B)

[[5 0]
 [6 4]]


### Exemple 2

Soient les matrices suivantes :

In [11]:
A=np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [12]:
B=np.array([[5],[2],[0]])
print(B)

[[5]
 [2]
 [0]]


`A@B` va donner la multiplication matricielle, et `A*B` va donner **une erreur** car  $A$ et $B$ ne sont pas de même dimension :

In [13]:
print(A@B)

[[ 9]
 [30]]


In [14]:
print(A*B)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

### Exemple 3

Soient les matrices suivantes :

In [15]:
A=np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [16]:
B=np.array([[5,0,3],[2,1,5]])
print(B)

[[5 0 3]
 [2 1 5]]


`A@B` va donner **une erreur** car le nombre de colonnes de $A$ n'est pas égal au nombre de lignes de $B$, et `A*B` va donner la multiplication terme à terme :

In [17]:
print(A@B)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [18]:
print(A*B)

[[ 5  0  9]
 [ 8  5 30]]


### Exemple 4

Soit la matrice suivante :

In [19]:
A=np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


L'opération `2*A` multiplie chaque élément de $A$ par 2 :

In [20]:
print(2*A)

[[ 2  4  6]
 [ 8 10 12]]


Tandis que `2@A` renverra une erreur car $2$ et $A$ ont des dimensions non compatibles :

In [21]:
print(2@A)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

### Exemple 5

Soit la matrice suivante :

In [2]:
A=np.array([[1,2],[4,5]])
print(A)

[[1 2]
 [4 5]]


Faire `A**2` signifie `A*A`, c'est à dire que tous les termes de la matrice sont élevés au carré. Code :

In [ ]:
print(A**2)

[[ 1  4]
 [16 25]]


Si maintenant on veut prendre le carré au point de vue matriciel, qui signifie `A@A`, la syntaxe est la suivante :

In [24]:
print(np.linalg.matrix_power(A,2))

[[ 9 12]
 [24 33]]


## 2.3 Manipulations matricielles de base

In [2]:
A=np.array([[1,1,2],[3,3,5],[4,7,8]])
print(A)

[[1 1 2]
 [3 3 5]
 [4 7 8]]


### Accéder aux éléments d'une matrice

In [26]:
print(A[1,1])   # les indices commencent à 0 !!!

3


In [27]:
print(A[1][1])    # équivalent

3


### Dimension, nombre d'éléments

In [28]:
print(A.shape)     # ou bien : np.shape(A)

(3, 3)


In [29]:
print(A.shape[0])   # nombre de lignes de la matrice A

3


In [30]:
print(type(A.shape)) # l'output est de type "tuple", voir chap. 3

<class 'tuple'>


In [31]:
print(A.size)       # Nombre d'éléments ; ou bien : np.size(A)

9


### Transposée, inverse, déterminant

In [3]:
print(np.transpose(A)) # calcule la transposée

[[1 3 4]
 [1 3 7]
 [2 5 8]]


In [4]:
Ainv=np.linalg.inv(A)    # matrice inverse
print(Ainv)

[[-3.66666667e+00  2.00000000e+00 -3.33333333e-01]
 [-1.33333333e+00 -0.00000000e+00  3.33333333e-01]
 [ 3.00000000e+00 -1.00000000e+00 -4.16333634e-17]]


In [5]:
print(np.linalg.det(A))

2.999999999999999


### Ajouter des éléments en fin de tableau : append

In [10]:
print(A)

[[1 1 2]
 [3 3 5]
 [4 7 8]]


In [35]:
A=np.append(A,[[1,2,3]],axis=0)    # axis = 0 => ajout d'une ligne
print(A)

[[1 1 2]
 [3 3 5]
 [4 7 8]
 [1 2 3]]


In [36]:
A=np.append(A,[[0],[0],[0],[0]],axis=1)    # axis = 1 => ajout d'une colonne
print(A)

[[1 1 2 0]
 [3 3 5 0]
 [4 7 8 0]
 [1 2 3 0]]


In [37]:
x=np.array([1,2,3])
x=np.append(x,4)         # avec tableaux 1D, pas besoin de spécifier axis
print(x)

[1 2 3 4]


### Insérer des éléments dans un tableau : insert

In [38]:
A=np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [39]:
B=np.array([[0,7],[8,9]])
print(B)

[[0 7]
 [8 9]]


In [40]:
A=np.insert(A,1,B,axis=1)     # Insertion de B selon les colonnes (axis=1) et AVANT la colonne 1 de A
print(A)

[[1 0 8 2]
 [3 7 9 4]]


## 2.4 Exercices

### Exercice 1

<ol>
    <li>Construisez la matrice $A$ donnée par 
\begin{equation}
A=Id+v^{t}.v
\end{equation}
    où $Id$ est la matrice identité et $v=(1,2,3,4,5,6,7,8,9,10)$ et $v^{t}$ est la transposée de $v$.</li>
    <li> Ajoutez $2$ à l'élément $A_{23}$.</li>
    <li> Vérifiez que la nouvelle matrice A est une matrice inversible.</li>
    <li>Construisez le vecteur $u$ défini par
\begin{equation}
u=w.A^3+4.v
\end{equation}
    où $w$ est un vecteur de même taille que $v$ dont les composantes sont le carré des composantes correspondantes de $v$.</li>
    <li>Remplacez la troisième composante de $u$ par le nombre $7$.</li>
     <li>Insérez le nombre $8$ entre la 2ème et 3ème composante de u et ajoutez un $0$ en fin de vecteur.</li>
</ol>

### Exercice 2

On considère l'équation de récurrence $f(n+1)=3f(n)-2f(n-1)$.
<ol>
<li>(Sur papier) Trouvez une matrice $A$ telle que 
\begin{equation}
    \left(
\begin{matrix}
f(n+1)\\
f(n)
\end{matrix}
\right)
=
A\left(
\begin{matrix}
f(n)\\
f(n-1)
\end{matrix}
\right) 
\end{equation}
</li>
<li>(Sur papier) En déduire l'expression matricielle de $\left(
\begin{matrix}
f(n+1)\\
f(n)
\end{matrix}
\right)$ en fonction de $\left(
\begin{matrix}
f(1)\\
f(0)
\end{matrix}
\right)$
</li>
<li>(Sur Python) En supposant que $f(0)=0$ et $f(1)=1$, calculez $f(14)$ via la relation matricielle.</li>
</ol>

### Exercice 3

Soit la suite 
\begin{eqnarray*}
x_{n+1}=-x_{n}+4x_{n-1}+4x_{n-2}\qquad n\in\{2,3,4,...\}
\end{eqnarray*}
avec les conditions initiales
\begin{eqnarray*}
x_0=1\quad x_1=0\quad x_2=0
\end{eqnarray*}
<ol>
    <li>Ecrire cette équation sous forme matricielle en fonction des conditions initiales.</li>
    <li>En déduire la valeur de $x_{10}$ via Python. 
</ol>

### Exercice 4

Chaque année, la population d'un pays fait son choix entre deux partis politiques : le parti A et le parti B. On constate les faits suivants:
- $1/3$ des anciens partisans de A sont mécontents et passent au parti B. Les autres anciens de A restent en A. 
- $1/4$ des anciens partisans de B restent en B et les autres passent en A.

<ol>
<li>(Sur papier) Exprimez par un système d'équations le mouvement politique de la population en 1 an.</li>
<li>(Sur papier) Exprimez ce transfert sous forme matricielle.</li>
<li>(Sur Python) Si en 1978 il y a 36000 partisans de A et 900 partisans de B, quelle sera la répartition en l'an 2000? </li>
</ol>

### Nota bene

Les exercices 2, 3 et 4 peuvent également être résolus par itérations, à l'aide de boucles `for` ou `while` : voir chapitre 4. 

## 2.5 Résolution d'un système linéaire

Pour résoudre un système linéaire carré inversible ``Ax=b``, la syntaxe est ``x=np.linalg.solve(A,b)``, à privilégier par rapport à ``x=np.inv(A)@b``. 

### Exercice 5

Astérix, Spirou, Kid Paddle et Gaston Lagaffe se rendent dans un Kebab. Astérix prend 8 assiettes gyros spéciales, 10 frites et 6 boissons. Il paie 43 euros. Spirou mange 2 frites et 2 boissons, mais ne prend pas d’assiette gyros spéciale, et il paie 9 euros. Kid Paddle se contente d’une assiette gyros spéciale et d’une boisson et paie 4.5 euros. Gaston Lagaffe voudrait prendre 1 assiette gyros spéciale avec 1 frite.<br>
Combien devra-t-il payer? Présentez la réponse proprement. 

### Exercice 6

Les 1500 salariés d’une entreprise sont répartis dans trois services A, B et C. Pour rééquilibrer les effectifs de ces trois services, il a été décidé que :
- 10\% des salariés du service B seront affectés au service C, les autres salariés de B restant en B. 
- 5\% des salariés du service A seront affectés au service B et 15\% au service C, les autres salariés de A restant en A. 
- Pas de transfert des salariés de C vers d'autres services. 

Après cette restructuration, le nombre de salariés du service B a diminué de 15 personnes et 159 salariés ont été mutés dans le service C.<br/>
On note A, B et C le nombre de salariés respectifs des trois services A, B et C <u><b>avant</b></u> la restructuration. On note A', B' et C' le nombre de salariés respectifs de ces trois services <u><b>après</b></u> la restructuration.
<ol>
<li>(Sur papier) Ecrire le problème sous forme de système linéaire.</li>
<li>Résoudre ce système avec Python pour déterminer A, B et C.</li>
<li>Afficher proprement A, B, C et A', B', et C'.</li>
</ol>